version: '3.9'
services:

  devredis:
    image: redis/redis-stack:latest
    restart: unless-stopped
    ports:
      - "6379:6379"
      - "8001:8001"

  adminui:
    image: opengartic/socketio.adminui
    restart: unless-stopped
    build:
      context: ./socketio.adminui
      dockerfile: Dockerfile
    ports:
      - "85:85"