version: '3.9'
services:

  redis:
    image: redis/redis-stack-server:latest
    restart: unless-stopped
    networks:
      - ognet

  backend:
    image: opengarlic/server
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - redis
    networks:
      - ognet

  frontend:
    image: opengarlic/client
    restart: unless-stopped
    build:
      context: ./client
      args:
        REACT_APP_SOCKET_SERVER: ${REACT_APP_SOCKET_SERVER}
        LE_DOMAIN: ${LE_DOMAIN}
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - nginx_certs:/etc/letsencrypt
      - nginx_challenge:/var/www/certbot
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - ognet

  adminui:
    image: opengartic/socketio.adminui
    restart: unless-stopped
    build:
      context: ./socketio.adminui
      dockerfile: Dockerfile
    ports:
      - "85:85"
    depends_on:
      - backend
    networks:
      - ognet

volumes:
  nginx_certs:
  nginx_challenge:

networks:
  ognet:
    driver: bridge