version: '3.8'
services:
  adminui:
    image: opengartic/socketio.adminui
    restart: unless-stopped
    build:
      context: ./socketio.adminui
      dockerfile: Dockerfile
    ports:
      - "85:85"
    networks:
      - adminnet

networks:
  adminnet:
    external:
      name: opengarlic_ognet